### ISSUE TITLE
Space complexity

### ISSUE THREAD

**Issue by ruslanbes** [kamyu104/GoogleCodeJam-2019#2]
Hi,

I'm wondering why for the 
https://github.com/kamyu104/GoogleCodeJam-2019/blob/master/Qualification%20Round/foregone-solution.py
and 
https://github.com/kamyu104/GoogleCodeJam-2019/blob/master/Qualification%20Round/you-can-go-your-own-way.py

the space complexity is O(1)

In the first case we need to store the number N which is logN-digit number so we need a space of O(logN) don't we? 

It would be O(1) if we were to read one digit, do the calculation and output it and then loop for the next.

In the second case we have the n-step path, so again we need the space of O(N) unless we do the similar stuff.

Or am I missing something?

**Comment by kamyu104** [comment]
The output space would be O(logn). So I usually only count the extra space without output.
